/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Sat, May 07, 2016                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53),    */
/*  and modified by Kazuyuki Hirooka.                                  */
/*                                                                     */
/***********************************************************************/
/************************************************************************
*
* Device     : RX/RX600/RX62N
*
* File Name  : hwsetup.c
*
* Abstract   : Hardware Setup file.
*
* History    : 1.00  (2010-03-05)  [Hardware Manual Revision : 0.50]
*
************************************************************************/

#include "iodefine.h"
#include "hwsetup_rx621.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif

void HardwareSetup(void)
{
    // AKI RX621

    //======================================================================
    // Clock source
    //  MAIN-XTAL 12MHz
    //======================================================================
    // ICLK:    96MHz   =  8 x 12MHz    // Max 100MHz
    // PCLK:    48MHz   =  4 x 12MHz    // Max  50MHz
    //----------------------------------------------------------------------
    SYSTEM.SCKCR.BIT.PCK    = 0x1;      // x4   // Peripheral clock
    SYSTEM.SCKCR.BIT.BCK    = 0x2;      // x2   // External Bus clock
    SYSTEM.SCKCR.BIT.PSTOP0 = 1;        // Stop // SDCLK(SDRAM CLK)
    SYSTEM.SCKCR.BIT.PSTOP1 = 1;        // Stop // BCLK(External BUS CLK)
    SYSTEM.SCKCR.BIT.ICK    = 0x0;      // x8   // Instruction, system, clock
    //----------------------------------------------------------------------

    PORT_init();

    MTU2_init();
    MTU2_ch0_restart();

    SCI_init();

    // ??? ADC_init();

    //============================================================
    // Interrupt Controller setting
    //============================================================
    // Interrupt Priority Level
    //  0:      prohibit interrupt
    //  1--15:  larger --> higher priority
    //------------------------------------------------------------
    IPR(MTU0,   TGIA0)      = 2;
    //  ??? IPR(S12AD,  S12ADI0)    = 3;
    //------------------------------------------------------------
    // Interrupt enable
    //------------------------------------------------------------
    IEN(MTU0,   TGIA0)      = 1;    // MTU0 interrupt: 0/1: disable/enable
    //  ??? IEN(S12AD,  S12ADI0)    = 1;    // Enable S12AD interrupt
    //------------------------------------------------------------


//--------------------------------------------------------------------------------
// Memo:
//
//*多重機能のピン設定
//  出力については周辺モジュールの出力設定によりそれが出力される。
//  競合するときは優先順位最高のものが出力される。
//      Ref: HW,    17.3 [100 ピンLQFP] I/O ポート
//                  17.3.3 ポートの設定
//                  17.3.4 出力許可設定一覧
//
//  e.g.:   PC3:    SCI5.SCR.TE = 1 で SCI5/TxD となる。
//----
//*Release module stop 必要
// リセット後は、DMACA、DTC、EXDMAC、内蔵RAM を除くすべてのモジュールがモジュールストップ
// 状態。
//      Ref: HW,    9.4 モジュールストップ機能
//
//  MSTP_xxxx register
//      b26 MSTPB26 シリアルコミュニケーションインタフェース5
//      モジュールストップ設定ビット
//      対象モジュール：SCI5
//      0：モジュールストップ状態の解除
//      1：モジュールストップ状態へ遷移
//----
//  SCMR.SMIF ビット=0 のとき、SCI はシリアルコミュニケーションインタフェースモードになり
//  ます。
//--------------------------------------------------------------------------------


}
