/***********************************************************************/
/*                                                                     */
/*  FILE        :rx621_sample.c                                        */
/*  DATE        :Sat, May 07, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  and modified by Kazuyuki Hirooka.                                  */
/*                                                                     */
/***********************************************************************/

//----------------------------------------
// Akizuki RX621 CPU board
// CPU chip: RF56218BDEP
// ROM 512KB   // FFF80000hÅ`FFFFFFFFh
// RAM 96KB    // 00000000hÅ`00017FFFh
//----------------------------------------

//----------------------------------------
// Akizuki RX220 CPU board
// CPU chip: RF52206BDFM
// ROM 256KB   // FFFC0000hÅ`FFFFFFFFh
// RAM 16KB    // 00000000hÅ`00003FFFh
//----------------------------------------

#include "iodefine.h"

#include "hwsetup_rx621.h"
#include "util.h"           // tcnt_show(), ms_abs_count_show()
#include "sci.h"
#include "mtu.h"
#include "etc.h"
#include "dft.h"
#include "fft_real_n_recur.h"
#include "stack_var_adrs.h"

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

//------------------------------------------------------------
// Global variables
//------------------------------------------------------------
int     g_ms_abs_count  = 0;
int     g_ms_count      = 0;    // g_ms_count={0, 1, ..., 999}
int     g_led0          = 0;    // 0 or 1

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

//  PORT2.DDR.BYTE      // port2/bit0, CN2/25, LED  0/1: OFF/ON

void main(void)
{
int     tx_done;
int     i;
int     ms_abs_count_prev;
int     dft_n;
int     preset_no;

    //--------------------------------------------------------------------------------
    // Variable size
    SCIprintf("sizeof(short) =%d\n", sizeof(short));
    SCIprintf("sizeof(int)   =%d\n", sizeof(int));
    SCIprintf("sizeof(int*)  =%d\n", sizeof(int*));
    SCIprintf("sizeof(long)  =%d\n", sizeof(long));
    SCIprintf("sizeof(float) =%d\n", sizeof(float));
    SCIprintf("sizeof(double)=%d\n", sizeof(double));
    if (sizeof(short)!=2) {
        SCIprintf("WARNING: sizeof(short)!=2.\n");
    }
    if (sizeof(double)!=8) {
        SCIprintf("WARNING: sizeof(double)!=8.\n");
    }
    //--------------------------------------------------------------------------------
    dft_address_show();
    fft_address_show();
    //--------------------------------------------------------------------------------
    stack_var_adrs_min_update();
    stack_var_adrs_min_show();

    //--------------------------------------------------------------------------------
    // MTU/ch3 TCNT test
    SCIprintf("MTU/ch3 TCNT test--------------------\n");
    for (i=0;i<8;i++) {
        ms_abs_count_prev = g_ms_abs_count;
        while (g_ms_abs_count==ms_abs_count_prev);
        ms_abs_count_prev = g_ms_abs_count;
        tcnt_restart();

        while (g_ms_abs_count==ms_abs_count_prev);
        tcnt_show("test", 1);
    }

    //--------------------------------------------------------------------------------
    // DFT/FFT test
switch(0) {
    case 0:
        //--------------------------------------------------------------------------------
        // Test of FFT over dft_n(>128), using auto-generated radix
        // on RX621
        // for (dft_n=4096;dft_n>=2048;dft_n-=4) {  // For test in float
        for (dft_n=2048;dft_n>=16;dft_n-=4) {
            fft_real_n_init(dft_n);
            if (g_fft_init_status!=0) continue; // Skip if FFT can not be performed.
            dft_init(dft_n);
            // //dft_test(0, 1);     // DFT RAW
            dft_test(1, 0);     // DFT with cos/sin table
            dft_test(2, 1);     // FFT
            stack_var_adrs_min_show();
        }
        break;
    default:
    case 1:
        //--------------------------------------------------------------------------------
        // Test of FFT over dft_n, using radix default
        for (dft_n=128;dft_n>=16;dft_n-=4) {
            dft_init(dft_n);
            fft_real_n_init(dft_n);
            //dft_test(0, 1);     // DFT RAW
            dft_test(1, 0);     // DFT with cos/sin table
            if (fft_real_default_n_available(dft_n)) { 
                dft_test(2, 0);     // FFT
            }
            stack_var_adrs_min_show();
        }
        break;
    case 9:
        //--------------------------------------------------------------------------------
        // FFT Tests over radix presets (for deciding radix default)
        //dft_n_prev = 0;
        for (i=0;i<=127;i++) {
            preset_no = i;
            //--------------------------------------------------------------------------------
            fft_real_init_by_preset(preset_no);
            dft_n = fft_real_get_npoint();
            dft_init(dft_n);
            // fft_real_radix_preset_tbl_mon(-1);   // -1: show all

            //if (dft_n==dft_n_prev) continue;
            //dft_test(0, 0);  // DFT RAW
            //dft_test(1, 0);  // DFT with cos/sin table
            fft_real_radix_preset_tbl_mon(preset_no, 0);
            // fft_real_radix_tbl_mon();
            dft_test(2, 0);     // 2:FFT, 1: show result
            //dft_n_prev = dft_n;
            stack_var_adrs_min_show();
        }
        break;
}

    //------------------------------------------------------------
    // Main loop
    //------------------------------------------------------------
    // LED
    MTU2_ch3_restart();
    i=0;
    tx_done = 0;
    while (1) {
        g_led0 = (g_ms_count>=500) ? 1 : 0;
        switch(tx_done) {
            default:
                if (g_ms_count>=500) {
                    SCIput('A'+(i%26));
                    tx_done=1;
                }
                break;
            case 1:
                if (g_ms_count<500) {
                    tx_done=0;
                    i++;
                    if ((i%16)==0) { 
                        SCIprintf("\n");
                    }
                }
                break;
        }
    }
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
